src/main/java/uk/gov/ons/census/action/messaging/EventReceiver.java, src/main/java/uk/gov/ons/census/action/model/dto/CollectionCase.java, src/test/java/uk.gov.ons.census.action/messaging/EventReceiverTest.java
The Action Scheduler might have complex Action Rules based on multiple attributes of a case, so we should store as much data as possible to enable these rules to be created.
Added a bunch of extra data from the CaseCreated event, stored on the case.
Run the acceptance tests. Check the Action Scheduler case database and make sure all the rows are populated with data from the sample.
Trello: https://trello.com/c/R9CmkZGf/626-update-the-action-service-to-contain-new-attributes-8
=> Store extra case attributes from CaseCreated message

src/main/resources/application.yml
The name of the queue from case processor to action scheduler has changed.
The name of the inbound queue.
Run the acceptance tests on the branch called `spike-topic-exchange` along with the Case Processor on the branch `spike-topic-exchange`.
Trello: https://trello.com/c/LQzjwQc2
=> Rename inbound queue

Dockerfile
The docker image `openjdk:11-slim` has changed the location of the `java` binary.
Changed the `java` path to the correct one.
Build the image. Container should start.
Trello: https://trello.com/c/7ivpCfY6
Reasons why stuff got broken: https://github.com/docker-library/openjdk/issues/320#issuecomment-494417274
=> Fix location of java after openjdk moved in docker image

.travis.yml
We are building and pushing our Docker images using Concourse instead of Travis. We need to stop Travis from pushing images, which are triggering extra deployments in Concourse which are not needed or wanted.
Removed the Docker image push from the Travis settings.
Merge to master. Travis shouldn't push to GCR.
Trello: https://trello.com/c/4chYCOrj
=> Remove Docker image push from Travis build

src/main/java/uk/gov/ons/census/action/builders/ActionInstructionBuilder.java, src/main/java/uk/gov/ons/census/action/schedule/ActionRuleProcessor.java, src/main/java/uk/gov/ons/census/action/schedule/ActionRuleScheduler.java, src/main/java/uk/gov/ons/census/action/schedule/ActionRuleTriggerer.java, src/test/java/uk/gov/ons/census/action/schedule/ActionRuleProcessorTest.java, src/test/java/uk/gov/ons/census/action/schedule/ActionRuleTriggererTest.java
Action Rules that were scheduled for exactly the same time would execute within a single transaction. Potentially that meant that we could be running a huge transaction for initial contact and other key events. By breaking each action rule execution into its own transaction, we reduce the memory footprint and the risk of rolling back useful work that has been done.
Added in an `ActionRuleTriggerer` class to allow the transaction boundaries to be delineated.
Run the acceptance tests - the change should cause no regression.
Trello: https://trello.com/c/5m9nDL4p
=> Break action rules into individual transactions

src/main/java/uk/gov/ons/census/action/builders/PrintFileDtoBuilder.java, src/main/java/uk/gov/ons/census/action/model/dto/PrintFileDto.java, src/test/java/uk/gov/ons/census/action/builders/PrintFileDtoBuilderTest.java
During WhiteLodge testing it was found the Questionnaire Management print files (E, W and NI) are currently holding the 'caseref' in the column that should contain 'coordinator_id'. 
coordinator_id is provided on the sample file, can range from 8 to 10 characters and is NOT mandatory
- Added `fieldCoordinatorId` to the outbound print message DTO
- Some Java magic probably
- `mvn clean install`
- Run against acceptance tests of the same branch name (fix-defect-969)
- https://github.com/ONSdigital/census-rm-acceptance-tests/pull/88
- https://github.com/ONSdigital/census-rm-print-file-service/pull/5
- [Trello card #969](https://trello.com/c/DxUlMxSc)
=> Defect #969: QM Print File - coordinator_id

src/main/java/uk/gov/ons/census/action/messaging/ActionFulfilmentReceiver.java, src/test/java/uk.gov.ons.census.action/messaging/ActionFulfilmentReceiverTest.java
Certain fulfilment codes don't get printed so action scheduler can ignore them.
Action scheduler now ignores fulfilment codes aren't print specific.
Run acceptance tests using branch of the same name and make sure UAC fulfilment codes don't cause action scheduler to error.
https://trello.com/c/yX4y7G8z/944-rmc-145b-implement-uac-fulfilment-event-part-a-13-part-b-5
=> Ignore fulfilment codes which action scheduler doesn't need to process

src/main/java/uk/gov/ons/census/action/builders/FieldworkFollowupBuilder.java, src/main/java/uk/gov/ons/census/action/messaging/EventReceiver.java, src/main/java/uk/gov/ons/census/action/model/dto/CollectionCase.java, src/main/java/uk/gov/ons/census/action/model/entity/Case.java, src/main/java/uk/gov/ons/census/action/schedule/ActionRuleProcessor.java, src/test/java/uk.gov.ons.census.action/messaging/ConsumeAndPublishIT.java, src/test/java/uk.gov.ons.census.action/messaging/EventReceiverTest.java
Fieldwork might discover that an address is not valid and notify RM via a message. We need to handle that message so that we cease doing follow-up actions and we know why we haven't had a response.
Excluded cases with invalid address from action plans.
Run the acceptance tests with Case Processor on the same branch name.
Trello: https://trello.com/c/bKxycLe3
=> Exclude cases with invalid address

src/main/java/uk/gov/ons/census/action/messaging/FulfilmentRequestReceiver.java, src/test/java/uk.gov.ons.census.action/messaging/FulfilmentRequestReceiverIT.java, src/test/java/uk.gov.ons.census.action/messaging/FulfilmentRequestReceiverTest.java
Members of a household need to be able to request continuation paper questionnaires
Added "P_OR_HC1", "P_OR_HC2", "P_OR_HC2W" & "P_OR_HC4" fulfilment codes
Added questionnaire type mapping for new codes
Added Continuation Questionnaire Fulfilment IT
Build local docker images of this branch and [this PR](https://github.com/ONSdigital/census-rm-print-file-service/pull/12) and run with docker dev
Run tests
Run acceptance tests from [this PR](https://github.com/ONSdigital/census-rm-acceptance-tests/pull/115)
[Trello](https://trello.com/c/SOmfsH8H/996-rmc-134c1-implement-continuation-pq-requested-event-5)
=> Implement Continuation PQ requested event

src/main/java/uk/gov/ons/census/action/builders/PrintFileDtoBuilder.java, src/main/java/uk/gov/ons/census/action/builders/QidUacBuilder.java, src/main/java/uk/gov/ons/census/action/model/UacQidTuple.java, src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java, src/main/java/uk/gov/ons/census/action/schedule/ActionRuleProcessor.java, src/test/java/uk.gov.ons.census.action/messaging/FulfilmentRequestReceiverIT.java, src/test/java/uk/gov/ons/census/action/builders/PrintFileDtoBuilderTest.java, src/test/java/uk/gov/ons/census/action/builders/QidUacBuilderTest.java, src/test/java/uk/gov/ons/census/action/schedule/ActionRuleProcessorIT.java, src/test/java/uk/gov/ons/census/action/schedule/ActionRuleProcessorTest.java
Action scheduler needs to schedule remind letters.
* Add action types for reminder letters
* Create new UAC QID pair for reminder pack codes
* Calculate questionnaire type from treatment code
* Unit tests for calculating questionnaire type and requesting new UAC QID pairs
Run a maven build on this branch, build the linked branch of print file service then run the linked branch of acceptance tests
https://trello.com/c/9WfpfHYE/721-rmc-138-schedule-generate-and-distribute-reminder-letters-5
https://github.com/ONSdigital/census-rm-print-file-service/pull/11
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/112
=> RMC-138 Scheduled Reminder Letters

src/main/java/uk/gov/ons/census/action/builders/PrintFileDtoBuilder.java, src/main/java/uk/gov/ons/census/action/builders/QidUacBuilder.java, src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java, src/main/java/uk/gov/ons/census/action/schedule/ActionRuleProcessor.java, src/test/java/uk/gov/ons/census/action/builders/PrintFileDtoBuilderTest.java, src/test/java/uk/gov/ons/census/action/builders/QidUacBuilderTest.java, src/test/java/uk/gov/ons/census/action/schedule/ActionRuleProcessorIT.java, src/test/java/uk/gov/ons/census/action/schedule/ActionRuleProcessorTest.java
We need to send scheduler reminder questionnaires.
* Add action types for reminder questionnaires
* Fetch second welsh UAC QID pair for welsh reminder questionnaire
Build and test with linked branches of print file service and acceptance tests.
https://trello.com/c/4GUC0HS0/723-rmc-157-schedule-generate-and-distribute-reminder-pqs-5
https://github.com/ONSdigital/census-rm-print-file-service/pull/13
=> RMC-157 Scheduled Reminder Questionnaires

src/main/java/uk/gov/ons/census/action/schedule/ActionRuleProcessor.java, src/test/java/uk/gov/ons/census/action/schedule/ActionRuleProcessorIT.java
Household Individual cases should not be used for Action reminders.
HI cases are not used when an action rule is triggered.
Run Action scheduler Integration tests.
Build Action Scheduler locally and run acceptance tests against Docker Dev.
https://trello.com/c/ErIhvPIp/1069-action-rules-to-ignore-hi-cases-3
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/121
=> No reminders for Household Individual cases.

src/main/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiver.java
Duplicate UAC QID pairs being created in Action Scheduler.
Don't create duplicates.
Run acceptance tests.
Trello: https://trello.com/c/MMPryFN7
=> Fix defect with duplicate UAC QID pairs being created

Dockerfile, src/main/java/uk/gov/ons/census/action/config/AppConfig.java, src/main/java/uk/gov/ons/census/action/config/MessageErrorHandler.java
We can't handle messages from FWMT due to strict JSON checking
Disabled strict JSON checking.
Hard to reproduce, but try this message:
```
{"event":{"type":"FULFILMENT_REQUESTED","source":"FIELDWORK_GATEWAY","channel":"FIELD","dateTime":"2019-09-13T14:22:34.327Z","transactionId":"3287c518-1898-406c-b55e-1e6138678550"},"payload":{"fulfilmentRequest":{"fulfilmentCode":"P_OR_H1","caseId":"02606dca-7f75-e911-abc4-0003ff39541c","address":{},"contact":{"title":null,"forename":null,"surname":null,"telNo":null}}}}
```
Trello: https://trello.com/c/MKGPgxP8
=> Fix for strict JSON checking

src/main/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiver.java, src/test/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiverTest.java
We had an Undelivered As Addressed (UAA) message for a case which was originally unaddressed, which is unusual, but prompted an investigation as to why we couldn't process it.
Update UAC-QID Link data in Action Scheduler to have case IDs, when unaddressed cases are linked.
Set an unaddressed UAC-QID pair, and then link it to a case. The case ID should be correctly linked in Action Scheduler.
Trello: https://trello.com/c/SCr4pzax
=> Fix bug where UAC/QID case ID not being updated when linked

src/main/java/uk/gov/ons/census/action/config/MessageConsumerConfig.java, src/main/java/uk/gov/ons/census/action/messaging/ManagedMessageRecoverer.java, src/main/resources/application.yml, src/test/java/uk/gov/ons/census/action/messaging/ManagedMessageRecovererTest.java, src/test/resources/definitions.json
We need to make RabbitMQ responsible for routing bad messages to a DLQ instead of manually doing this in our application code. This PR makes use of `AmqpRejectAndDontRequeueException` to reject a bad message, allowing Rabbit to take care of routing and redelivering that message.
* Reject the message by throwing an exception
* Remove retry exchange from code 
* Suppress 'noisy' stack trace logging at warning level when the exception is thrown
*  Update tests and test queue config
Build this branch, checkout the [docker-dev PR](https://github.com/ONSdigital/census-rm-docker-dev/pull/40) and post a bad message to a queue this service consumes from. Check the message is redelivered continuously.
https://trello.com/c/hG9Mi8tA/315-rabbit-message-persistence-dlq-config-8
=> Rabbit msg persistence dlq config

src/main/java/uk/gov/ons/census/action/service/FulfilmentRequestService.java
We have created a new RM internal fulfilment code for individual household telephone capture which action scheduler needs to ignore.
* Add RM_TC_HI to list of ignored fulfilment codes
Build and run this branch with the other branches and acceptance tests for this feature. Check that after the test run, action scheduler has not logged any unknown fulfilment codes.
https://trello.com/c/UJpW7I1J/484-rmc-335-telephone-capture-hi-13
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/156
https://github.com/ONSdigital/census-rm-case-api/pull/47
https://github.com/ONSdigital/census-rm-case-processor/pull/95
=> Ignore RM internal fulfilment code for HI telephone capture

src/main/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiver.java, src/main/java/uk/gov/ons/census/action/model/dto/CollectionCase.java, src/main/java/uk/gov/ons/census/action/model/entity/Case.java, src/main/java/uk/gov/ons/census/action/model/entity/CaseState.java, src/test/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiverTest.java
We can now safely remove the redundant case `state` column from our schemas
Removed `state` from the repo
Make sure tests and acceptance tests still pass from the links below
https://trello.com/c/dBJe87ZS/481-get-rid-of-casestate-from-case-table-8
https://github.com/ONSdigital/census-rm-case-processor/pull/101
https://github.com/ONSdigital/census-rm-case-api/pull/53
https://github.com/ONSdigital/census-rm-action-worker/pull/9
https://github.com/ONSdigital/census-rm-ddl/pull/32
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/169
=> Remove case state

src/main/java/uk/gov/ons/census/action/builders/FieldworkFollowupBuilder.java, src/main/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiver.java, src/main/java/uk/gov/ons/census/action/model/dto/CollectionCase.java, src/main/java/uk/gov/ons/census/action/model/dto/FieldworkFollowup.java, src/main/java/uk/gov/ons/census/action/model/entity/Case.java, src/test/java/uk/gov/ons/census/action/builders/FieldworkFollowupBuilderTest.java, src/test/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiverTest.java
We need to add `handDeliver` bool flag on each of our outgoing Action Instruction `CREATE` messages to Field. 
Added flag to field followup messages
Check build, run ATs against links below
https://trello.com/c/esdStYzJ/514-rmc-317-make-hand-delivery-flag-in-outbound-field-messages-dynamic-based-on-treatment-code-8
https://github.com/ONSdigital/census-rm-fieldwork-adapter/pull/30
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/191
https://github.com/ONSdigital/census-rm-ddl/pull/38
https://github.com/ONSdigital/census-rm-action-worker/pull/10
https://github.com/ONSdigital/census-rm-case-processor/pull/112
=> RMC-317: Add handDelivery on outbound messages

src/main/java/uk/gov/ons/census/action/service/FulfilmentRequestService.java
The Lithuanian NI translation booklet code is wrong (source documentation is was copied from was incorrect and has since been fixed).
Fix incorrect fulfilment code for NI Lithuanian translation booklet
Request a `P_TB_TBLIT4` fulfilment
Build and run linked AT's branch
https://trello.com/c/2k5jYnrw/648-defect-lithuanian-translation-booklet-fulfilment-code-incorrect-for-ni#
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/195
=> Fix incorrect fulfilment code for NI Lithuanian translation booklet

src/main/java/uk/gov/ons/census/action/builders/CaseSelectedBuilder.java, src/main/java/uk/gov/ons/census/action/builders/FieldworkFollowupBuilder.java, src/main/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiver.java, src/main/java/uk/gov/ons/census/action/messaging/UndeliveredMailReceiver.java, src/main/java/uk/gov/ons/census/action/model/dto/FieldCaseSelected.java, src/main/java/uk/gov/ons/census/action/model/dto/PrintCaseSelected.java, src/main/java/uk/gov/ons/census/action/model/dto/PrintFileDto.java, src/main/java/uk/gov/ons/census/action/model/entity/Case.java, src/main/java/uk/gov/ons/census/action/model/repository/CaseRepository.java, src/test/java/uk/gov/ons/census/action/builders/FieldworkFollowupBuilderTest.java, src/test/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiverTest.java, src/test/java/uk/gov/ons/census/action/messaging/UndeliveredMailReceiverIT.java, src/test/java/uk/gov/ons/census/action/messaging/UndeliveredMailReceiverTest.java
caseRef to 10
caseRef becomes a long
with ATs from ticket
https://trello.com/c/J7ZhdBtv/661-convert-case-ref-from-int-to-long-in-case-api-action-exporter-action-worker-13
=> caseRef from Integer to Long

src/main/java/uk/gov/ons/census/action/builders/FieldworkFollowupBuilder.java, src/main/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiver.java, src/main/java/uk/gov/ons/census/action/model/dto/Address.java, src/main/java/uk/gov/ons/census/action/model/dto/CollectionCase.java, src/main/java/uk/gov/ons/census/action/model/dto/FieldworkFollowup.java, src/main/java/uk/gov/ons/census/action/model/entity/Case.java, src/test/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiverTest.java
ARID is dead. Long live ARID. May estab UPRN have a long and victorious reign.
ARID has been removed. Estab ARID has been usurped by Estab UPRN.
Run the ATs along with all the other PRs on the ticket.
Trello: https://trello.com/c/zm2Ssvnn
=> Remove ARID and replace estab ARID with estab UPRN

.gitignore, src/main/java/uk/gov/ons/census/action/service/FulfilmentRequestService.java, src/test/java/uk/gov/ons/census/action/service/FulfillmentRequestServiceTest.java
Since cases can now be created on the fly with unvalidated potentially incomplete data we now need to protect against fulfilment requests on cases without sufficient address data.
* Add check for mandatory fields in cases being requested for fulfilments
* Add unit tests
Build and run with linked AT's branch.
https://trello.com/c/C6Y53PdB/709-am1-part-4-new-address-request-paper-fulfilment-5
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/227
=> AM1 Part 4 New Address Fulfilments

src/main/java/uk/gov/ons/census/action/schedule/CaseClassifier.java, src/test/java/uk/gov/ons/census/action/schedule/ActionRuleProcessorIT.java, src/test/java/uk/gov/ons/census/action/schedule/CaseClassifierTest.java
We don't want skeleton cases to be included when action plans run.
Clause added to statement where rows are excluded if skeleton is true. Tests added and updated.
Check branch builds and run alongside [acceptance tests branch of the same name](https://github.com/ONSdigital/census-rm-acceptance-tests/pull/250).
https://trello.com/c/ThiV27TP/741-exclude-skeleton-cases-from-action-plans-3
=> exclude skeleton cases from action plans

src/main/java/uk/gov/ons/census/action/service/FulfilmentRequestService.java
Added fulfilment codes for translation booklets.
- Added new codes for translation booklets
- Removed 1 code that's no longer in the spec
- Run the `translation-fulfilment-mappings` branch of acceptance tests against this branch and `translation-fulfilment-mappings` branch of print-file-service
- https://trello.com/c/um0MQpJJ
- https://github.com/ONSdigital/census-rm-print-file-service/pull/46
- https://github.com/ONSdigital/census-rm-acceptance-tests/pull/264
- https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=SDC&title=RM+Product+Library
=> Add translation booklet fulfilment codes

pom.xml, src/main/java/uk/gov/ons/census/action/Application.java, src/main/java/uk/gov/ons/census/action/model/repository/FulfilmentToSendRepository.java, src/main/resources/application.yml
As part of the 'big bang' work I flipped the healthcheck from using Actuator to using the file-based healthcheck, because we don't want to expose the REST API used by the Ops tool in the production environment: we should remove it altogether at some future point, to reduce the attack surface.
When using the file-based healthcheck, which is driven by a scheduled job, there's the possibility of the single thread used by default for scheduling, being blocked by the long-running action rules. This causes K8S to think the application is unhealthy, and therefore will reboot the pod.
I already thought of this issue and implemented a fix for it back in December 2019: https://github.com/ONSdigital/census-rm-action-scheduler/pull/57/files
Increased the number of scheduling threads.
Do a Census. …
=> Fix healthcheck thread starvation causing K8S pod restart

src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java, src/main/java/uk/gov/ons/census/action/schedule/CaseClassifier.java
These ActionTypes needed to be changed to generate and address line for each instance of expected response recorded against the unit whereas before they were not dependent on expected capacity
ActionTypes added to appropriate class
Build with other repos on card and run ATs
https://trello.com/c/FPqeHTfQ/1046-ic031-i041-generate-ce-unit-addressed-icl-print-files-3
https://collaborate2.ons.gov.uk/confluence/display/SDC/RM+Census+Initial+Contact+Run+Book+-+2021
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?pageId=34832584
=> (IC03.1/IC04.1) Generate CE UNIT Addressed ICL Print Files 

src/main/java/uk/gov/ons/census/action/model/entity/ActionRule.java, src/main/java/uk/gov/ons/census/action/schedule/CaseClassifier.java, src/test/java/uk/gov/ons/census/action/schedule/ActionRuleProcessorIT.java, src/test/java/uk/gov/ons/census/action/schedule/ActionRuleProcessorTest.java, src/test/java/uk/gov/ons/census/action/schedule/CaseClassifierTest.java
Allow filtering on more complex criteria that json classifiers, in this case on date for address frame delta
Rather than take, expect, store and create SQL from json classifiers, this now expects a userDefinedWhereClause, 
e.g. "treatment_code IN ('sdsd')", this is then appended to the hardcoded filters
The hardcoded filter of caseType != 'HI' has also been removed
mvn clean install and with other branches and tests from this ticket
https://trello.com/c/TnldEmYZ/1023-address-frame-delta-generate-additional-initial-contact-files-13
=> 1023 address frame delta generate additional initial contact files

src/main/java/uk/gov/ons/census/action/model/entity/ActionRule.java
Text column didn't play nicely with ops tool or show nicely in DB
Made column type a Byte Array
Should work nicely with existing ATs (needs action-worker from this ticket installed).  Check that the ops tool works with it, check that the action rules are readable in the database (this wasn't the case with a TEXT column).
https://trello.com/c/ye66Hup7/1159-make-classifierclause-a-varchar
=> make classfierClause a byte array

src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java, src/main/java/uk/gov/ons/census/action/model/entity/CaseMetadata.java
The case metadata can now contain the channel of creation for HI cases.
* Add individual reminder action types 
* Update case metadata entity
At AT's PR
https://trello.com/c/Rc8d1RmE/983-reminders-individual-response-8
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/296
=> Add action types and update case metadata entity

src/main/java/uk/gov/ons/census/action/model/entity/Case.java, src/main/java/uk/gov/ons/census/action/model/entity/UacQidLink.java, src/test/java/uk/gov/ons/census/action/schedule/ActionRuleProcessorIT.java
Use UUID data type to hold UUID data
Updated entity and a few tests.
- Build it and run it against the acceptance tests (master), with `use-UUID-type-for-UUId-data` branches of DDL, case-processor, case-api, action-worker and action-processor.
- https://trello.com/c/r9qwqhaS
=> Use UUID type for UUID data

src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java, src/main/java/uk/gov/ons/census/action/schedule/ActionRuleTriggerer.java
In the unlikely event that we are free-hand hacking SQL into the action rules in prod, completely untested in preprod, it's _theoretically_ possible that the bad action rule could block other action rules. In practice, this will never happen, because we don't hack rubbish into production in an uncontrolled manner.
In reality, this is a request for a debugger to deal with testers creating bad action rules, not a feature for the Census.
Log an error but don't block other action rules.
Create a bunch of action rules, including a bad one. The bad one shouldn't block the good ones.
Trello: https://trello.com/c/nWJmBc0D
=> Log error but don't block other action rules on exception

src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java
There was a mistake on the Reminder Run Book for 2021.
Swapped pack codes for NI reminders, per change request.
Run the ATs.
Trello: https://trello.com/c/E6s4HoxU
=> Swap pack codes for NI reminders

src/main/java/uk/gov/ons/census/action/model/entity/Case.java
When an AddressTypeChange event occurs where the new address is a CE Case, the ceActualResponses is null rather than 0 
Changed ceActualResponses from Integer to int so now defaults to 0 instead of null
Maven clean install on branch and check image builds and tests pass
https://trello.com/c/DUgevj8y
=> AddressTypeChange for CE Case ceActualResponses Defaulted to Zero

src/main/java/uk/gov/ons/census/action/schedule/ActionRuleTriggerer.java, src/main/java/uk/gov/ons/census/action/schedule/FulfilmentProcessor.java, src/main/java/uk/gov/ons/census/action/schedule/FulfilmentScheduler.java, src/main/resources/application.yml
The action scheduler doesn't do much - most of the work is done by Cloud SQL (Postgres) - and as such, it can be hard to know if it's doing what it's supposed to or not.
Added info logging to the action rules and fulfilments so that we know when they've triggered... although it may take quite a while before the database transaction commits and the action workers spring into action.
Run the ITs and/or ATs and you'll see the extra info logging.
Trello: https://trello.com/c/g1pelaNc
=> Add useful info logging when rules and fulfilments trigger
