src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java

Changed Action Type code for Wales Initial Contact Letter.
Test with equivalent branch on Action Scheduler and Action Exporter.

Change Wales ICL action type code.

---

src/main/java/uk/gov/ons/census/action/messaging/EventReceiver.java
src/main/java/uk/gov/ons/census/action/model/dto/CollectionCase.java
src/main/java/uk/gov/ons/census/action/model/entity/Case.java
src/main/resources/application.yml
src/test/java/uk.gov.ons.census.action/messaging/EventReceiverTest.java

Part of the 3 new fields required for final rehearsal sample spec
https://trello.com/c/CzpZXxpZ/741-update-case-data-model-to-reflect-final-rehearsal-sample-8#
To test this you can run mvn clean install
Also with the other branches in the PR images created run the related acceptance-tests
https://trello.com/c/CzpZXxpZ/741-update-case-data-model-to-reflect-final-rehearsal-sample-8
CASE API:
https://github.com/ONSdigital/census-rm-case-api/tree/rehearsal-sample-spec
ACTION SCH:
https://github.com/ONSdigital/census-rm-action-scheduler/pull/6/files
CASE-PROCERSSOR:
https://github.com/ONSdigital/census-rm-case-processor/pull/11
& new tests:
https://github.com/ONSdigital/census-rm-acceptance-tests/tree/rehearsal-sample-spec

added rehearsal spec fields

---

src/main/java/uk/gov/ons/census/action/schedule/ActionRuleProcessor.java
src/test/java/uk.gov.ons.census.action/messaging/ConsumeAndPublishIT.java
src/test/java/uk/gov/ons/census/action/builders/PrintFileDtoBuilderTest.java

The Wales pack code was incorrect. This PR fixes it.
The pack code has been updated where in all places it is used.
Build image of this branch, build the image of the printfilesvc branch that has the same name and run the acceptance tests that also have the same branch name.
Look to see if the files in the sftp folder have the updated name.
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/85
https://github.com/ONSdigital/census-rm-print-file-service/pull/3
https://trello.com/c/DWs4rrCc/925-correct-product-pack-code-for-initial-contact-pack-for-welsh-households-3

Correcting Wales ICL pack code

---

src/main/java/uk/gov/ons/census/action/builders/FieldworkFollowupBuilder.java
src/main/java/uk/gov/ons/census/action/model/dto/FieldworkFollowup.java
src/main/java/uk/gov/ons/census/action/schedule/ActionRuleProcessor.java
src/test/java/uk/gov/ons/census/action/builders/ActionInstructionBuilderTest.java
src/test/java/uk/gov/ons/census/action/builders/FieldworkFollowupBuilderTest.java
src/test/java/uk/gov/ons/census/action/schedule/ActionRuleProcessorTest.java

FWMT need these three values to be populated.
Add assertions for hardcoded mandatory fields for FWMT
Tests should pass. Run against the acceptance tests and fieldwork-adapter branches linked below.
https://github.com/ONSdigital/census-rm-fieldwork-adapter/pull/3
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/94
Trello card: https://trello.com/c/eBLq71pk/997-fwmt-missing-fields

ADD FWMT missing fields

---

src/main/java/uk/gov/ons/census/action/builders/CaseSelectedBuilder.java
src/main/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiver.java
src/main/java/uk/gov/ons/census/action/messaging/FulfilmentRequestReceiver.java
src/main/java/uk/gov/ons/census/action/schedule/ActionRuleProcessor.java
src/main/resources/application.yml
src/test/java/uk.gov.ons.census.action/messaging/FulfilmentRequestReceiverIT.java
src/test/java/uk.gov.ons.census.action/messaging/FulfilmentRequestReceiverTest.java
src/test/java/uk/gov/ons/census/action/schedule/ActionRuleProcessorTest.java

We want to know what pack code has been used on a fulfilment request.
Send a message to Case Processor when we print an adhoc fulfilment request.
Run the ATs against the same branch name
Trello: https://trello.com/c/3xvFQbvw

Notify case of PRINT_CASE_SELECTED on fulfilment

---

src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java
src/main/java/uk/gov/ons/census/action/schedule/ActionRuleProcessor.java

for response driven lsoa reminders
New mappings for new ActionTypes and Packcodes
Test with ATs and printsvc on same branch
https://trello.com/c/EIr1NVJi/1119-rmc-187a-processing-response-driven-interventions-5

add mappings and actionTypes for response driven

---

src/main/java/uk/gov/ons/census/action/builders/QidUacBuilder.java
src/main/java/uk/gov/ons/census/action/config/MessageErrorHandler.java
src/main/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiver.java
src/main/java/uk/gov/ons/census/action/messaging/UndeliveredMailReceiver.java
src/main/resources/application.yml

Without the stack traces, some of the errors would say little more than "Runtime exception" and be very hard to diagnose and fix.
Added descriptive text to all RuntimeExceptions. Added option to print stack traces which can be toggled on to diagnose difficult problems.
Try toggling the setting in application.yml and set off some exceptions.
Trello: https://trello.com/c/KViVYGvP

Improve logging

---

src/main/java/uk/gov/ons/census/action/config/AppConfig.java

All rabbit channels should be transactional
updated the rabbit config in AppConfig.java to make sure all rabbit channels are transactional
start up service, go to the "channels" tab in the management UI and all channels from this app should be marked as transactional ("T" in the mode column)

update rabbit config to make all channels transactional

---

src/main/java/uk/gov/ons/census/action/builders/FieldworkFollowupBuilder.java
src/main/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiver.java
src/main/java/uk/gov/ons/census/action/model/dto/CollectionCase.java
src/main/java/uk/gov/ons/census/action/model/dto/FieldworkFollowup.java
src/main/java/uk/gov/ons/census/action/model/entity/Case.java
src/test/java/uk/gov/ons/census/action/builders/FieldworkFollowupBuilderTest.java
src/test/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiverTest.java

New field ceActualResponses 
Added new field & changed ceExpectedCapacity to an Integer
mvn clean install
& run ATs with other apps installed
https://trello.com/c/i8X8YCZM/452-rmc-317-send-ce-estab-job-to-field-13

452 rmc 317 send ce estab job to field

---

pom.xml
src/main/java/uk/gov/ons/census/action/builders/FieldworkFollowupBuilder.java

Now when we run mvn_clean_install all the changed files are formatted so they wont fail at Travis build
Included format execution goal in pom file
Clone then change a file to improper formatting and then run tests and git push it to see if Travis checks pass
https://trello.com/c/CAEpFpzY

Updating execution goal to format files

---

src/main/java/uk/gov/ons/census/action/service/FulfilmentRequestService.java

Ignore RM_TC fulfilments
Ignores RM_TC 
With AT and case-api from this ticket
https://trello.com/c/fRwTHZam/483-rmc-335-log-telephone-capture-request-5

added non HI RM_TC to ignore list

---

src/main/java/uk/gov/ons/census/action/model/entity/ActionRule.java
src/main/java/uk/gov/ons/census/action/model/entity/Case.java
src/main/java/uk/gov/ons/census/action/model/entity/UacQidLink.java

Hibernate does not set up the same database config in a dev GCP env as it does in an env built from the DDL scripts.
Fixed mismatches.
Build and run into empty database. Using a **reliable** DB inspection tool (i.e. not DataGrip) check the missing indexes are present.
Trello: https://trello.com/c/ybEYuI66

Add missing indexes and fix other DDL mismatch

---

pom.xml
src/main/java/uk/gov/ons/census/action/builders/FieldworkFollowupBuilder.java
src/main/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiver.java
src/main/java/uk/gov/ons/census/action/model/dto/CollectionCase.java
src/main/java/uk/gov/ons/census/action/model/dto/FieldworkFollowup.java
src/main/java/uk/gov/ons/census/action/model/entity/Case.java
src/main/java/uk/gov/ons/census/action/model/entity/CaseMetadata.java
src/main/java/uk/gov/ons/census/action/service/FulfilmentRequestService.java
src/test/java/uk/gov/ons/census/action/builders/FieldworkFollowupBuilderTest.java
src/test/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiverTest.java

New column for identifying if CE case is a Secure Establishment
New Metadata column which will be used to group CE/SPG details that aren't constants in the JSON
Tests
Clone the branch and run ```maven clean install``` which will build the image
https://collaborate2.ons.gov.uk/confluence/display/CRM/Address+Frame+specification+2021?focusedCommentId=36183836#comment-36183836
https://trello.com/c/BAI9qOOC/619-rmc-341-add-secure-marker-case-api-and-field-8

Add CE Secure Marker

---

src/main/java/uk/gov/ons/census/action/builders/FieldworkFollowupBuilder.java
src/main/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiver.java
src/main/java/uk/gov/ons/census/action/model/dto/CollectionCase.java
src/main/java/uk/gov/ons/census/action/model/dto/FieldworkFollowup.java
src/main/java/uk/gov/ons/census/action/model/entity/Case.java
src/test/java/uk/gov/ons/census/action/builders/FieldworkFollowupBuilderTest.java

Undelivered as addressed marker has been removed
Undelivered as addressed marker removed along with any where it is set.
Build images for each of the repos on the trello ticket and run acceptance tests.
https://trello.com/c/gpxiNXHt/758-rmc-345-ce-and-spg-uaa-8

remove unaddressed as delivered flag

---

src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java

new ActionTypes for CE1
Added new ActionTypes
As part of ticket
https://trello.com/c/H1lzyyIr/472-ic01-ic02-generate-ce1-addressed-print-files-8

ActionTypes for CE1

---

src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java

Want to generate individual addressed initial contact letters for CE Units
Added ActionTypes
Build and run with other repos and then run ATs
https://trello.com/c/GEPhT08E/787-ic031-i041-generate-ce-unit-addressed-icl-print-files-3

Generate CE Unit Addressed ICL Print Files

---

src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java
src/main/java/uk/gov/ons/census/action/model/entity/CaseToProcess.java
src/main/java/uk/gov/ons/census/action/model/repository/CaseRepository.java
src/main/java/uk/gov/ons/census/action/schedule/CaseClassifier.java
src/test/java/uk/gov/ons/census/action/schedule/ActionRuleProcessorIT.java
src/test/java/uk/gov/ons/census/action/schedule/CaseClassifierTest.java

Want to generate individual addressed initial contact letters for CE Estab cases
Added ActionTypes
New column in CaseToProcess
New method to distinguish CE Estab cases via pack codes
Tests
Build and run with other repos and then run ATs
https://trello.com/c/0WUGJq8e/471-ic03-ic04-generate-ce-estab-individual-addressed-print-files-21

Generate CE Estab Addressed ICL Print Files

---

src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java

Want to generate individual addressed initial contact letters for SPG Units
New ActionTypes included
Build and run with other repos and then run ATs
https://trello.com/c/1gqkpqmf/809-ic11-ic12-generate-spg-addressed-icl-print-files-5

Generate SPG Unit Addressed ICL Print Files

---

src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java
src/main/java/uk/gov/ons/census/action/schedule/CaseClassifier.java

Added the action types needed for NI CE Estab Individual letters and paper questionnaires
- Added in the action types
- Run with `mvn clean install` and tests should pass
- Run ATs with other branches and tests should pass
[Trello](https://trello.com/c/aRah4j2n)

Rmc 270 271 ce estab ni individual letter and pqs

---

src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java

Want to generate individual addressed initial contact questionnaires for SPG Units in English and Welsh
New ActionTypes/PackCodes included
Build and run with other repos and then run ATs
https://trello.com/c/nxTRcBaY/808-ic13-ic14-generate-spg-addressed-ic-pq-print-files-13

IC13/IC14 Generate SPG Unit Addressed PQs

---

src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java
src/main/java/uk/gov/ons/census/action/service/FulfilmentRequestService.java
src/test/java/uk/gov/ons/census/action/service/FulfillmentRequestServiceTest.java

New fulfilment codes for different scenarios added to run book so repos need updating
New actiontype
New fulfilment codes/mappings
Tests
Build and run with ATs
https://trello.com/c/3OoO0Mx9/888-fulfilment-mappings-hh-print-products-5
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=SDC&title=RM+Product+Library

8-15 and 24-26 HH Print Fulfilment Codes

---

src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java
src/main/java/uk/gov/ons/census/action/service/FulfilmentRequestService.java
src/test/java/uk/gov/ons/census/action/service/FulfillmentRequestServiceTest.java

New fulfilment codes for Easy Read Information Leaflets
New actiontype
New fulfilment codes/mappings
Tests
Build and run with ATs
https://trello.com/c/um0MQpJJ/945-fulfilment-mappings-easy-read-products-5
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=SDC&title=RM+Product+Library

42-43 Information Leaflet Fulfilment Codes

---

src/main/java/uk/gov/ons/census/action/messaging/FulfilmentRequestReceiver.java
src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java
src/main/java/uk/gov/ons/census/action/service/FulfilmentRequestService.java

Added new individual response UAC print product codes so it'll send to the print file service when theres been a fulfilment.
- Added new individual response UAC fulfilments
- Run `mvn clean install` and all tests should pass
- Run the ATs with other branches and they should pass
[Trello](https://trello.com/c/2pVJow0S)

Added new fulfilment mappings

---

src/main/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiver.java
src/main/java/uk/gov/ons/census/action/model/dto/CollectionCase.java
src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java
src/main/java/uk/gov/ons/census/action/model/entity/Case.java
src/test/java/uk/gov/ons/census/action/messaging/CaseAndUacReceiverTest.java

New survey launched flag
https://trello.com/c/jRDDwnf8/981-reminders-started-eq-but-not-submitted-13

updated models

---

src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java

User needs to be able to request questionnaire in large print format at HH/Individual level
No required UAC/QID pair
New ActionType
Build docker image along with other repos on card and run ATs
https://trello.com/c/Pil5FSiZ/944-fulfilment-mappings-large-print-products-hh-ind-5
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=SDC&title=RM+Product+Library
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=SDC&title=Print+and+Post+Specification+2021
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=SDC&title=Operational+Notes

Fulfilment Mappings - Large Print Questionnaires: HH/Ind

---

src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java

Additional paper fulfillments.  See https://collaborate2.ons.gov.uk/confluence/display/SDC/RM+Product+Library - rows 35-37, 41-42.
New action type for the CE codes.
Run the `additional-paper-uac-fulfilments` branch of acceptance tests against this branch and the equivalent branches of case-processor, action-processor, action-scheduler and printfile service.
https://trello.com/c/TRqlAbsI

Additional paper UAC fulfilments

---

src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java
src/main/java/uk/gov/ons/census/action/model/entity/CaseMetadata.java

Adding two new reminder pack codes
Two new pack codes have been added mainly as enums throughout the software.

adding new reminder pack codes

---

src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java
src/main/java/uk/gov/ons/census/action/model/entity/FulfilmentToProcess.java
src/main/java/uk/gov/ons/census/action/model/entity/FulfilmentType.java
src/main/java/uk/gov/ons/census/action/schedule/CaseClassifier.java

The pack code descriptions were badly out of alignment with our documentation, and some have become redundant since the rehearsal.
Updated the pack code descriptions and deleted dead pack codes.
Run full regression ATs.
Trello: https://trello.com/c/J1Gr5PNq

Update pack code descriptions

---

src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java

RM will be given lists of LSOAs to generate response-driven reminders for. This PR adds new action types / pack codes.
Added new pack codes
See Toolbox PR
https://trello.com/c/tRiFtYj5/984-reminders-response-driven-8

Add response-driven reminder pack code mappings

---

src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java
src/main/java/uk/gov/ons/census/action/model/entity/CaseMetadata.java
src/main/java/uk/gov/ons/census/action/model/entity/NonComplianceType.java

Add non compliance types
Non compliance types added
Run with all the other PRs on linked tickets
https://trello.com/c/r6x95aJS/1405-nc-import-letter-file-1-print-file-work-8

add non compliance types
